// <auto-generated />
using LearnExcelToSQLUsingDotNet.DatabaseContextOptions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnExcelToSQLUsingDotNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearnExcelToSQLUsingDotNet.Models.ColumnDefinition", b =>
                {
                    b.Property<int>("ColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColumnId"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColumnId");

                    b.ToTable("ColumnDefinition");
                });

            modelBuilder.Entity("LearnExcelToSQLUsingDotNet.Models.PriceCalculation", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Name");

                    b.ToTable("PriceCalculation");
                });

            modelBuilder.Entity("LearnExcelToSQLUsingDotNet.Models.TransactionData", b =>
                {
                    b.Property<int>("TRAN_ID")
                        .HasColumnType("int");

                    b.Property<string>("ACCOUNT_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ACQUIRER_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AMOUNT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DATE_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ERR_DESC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISSUER_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LEDGER_BALANCE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MESSAGE_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OLD_ACQUIRER_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OLD_DATE_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OLD_TRACE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORIGINATOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSTING_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESP_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SYS_DATE_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TERM_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRACE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TRAN_CHARGE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TRAN_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VCH_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WAIVER_AMOUNT")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TRAN_ID");

                    b.ToTable("TransactionDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
