--INDEX REORGANIZE SCRIPT WHOSE FRAGMENTATION IS >40

SELECT	S.NAME AS 'SCHEMA',
		T.NAME AS 'TABLE',
		I.NAME AS 'INDEX',
		DDIPS.AVG_FRAGMENTATION_IN_PERCENT,
		DDIPS.PAGE_COUNT,
		'ALTER INDEX '+I.NAME+' ON '+T.NAME+' REORGANIZE; PRINT CONCAT(CONVERT(VARCHAR(50),GETDATE(),113),'' '','''+T.NAME+''','' '','''+I.NAME+''')'
FROM SYS.DM_DB_INDEX_PHYSICAL_STATS (DB_ID(), NULL, NULL, NULL, NULL) AS DDIPS
	INNER JOIN SYS.TABLES T ON T.OBJECT_ID = DDIPS.OBJECT_ID
	INNER JOIN SYS.SCHEMAS S ON T.SCHEMA_ID = S.SCHEMA_ID
	INNER JOIN SYS.INDEXES I ON I.OBJECT_ID = DDIPS.OBJECT_ID AND DDIPS.INDEX_ID = I.INDEX_ID
WHERE DDIPS.DATABASE_ID = DB_ID() AND I.NAME IS NOT NULL AND DDIPS.AVG_FRAGMENTATION_IN_PERCENT > 40
ORDER BY DDIPS.AVG_FRAGMENTATION_IN_PERCENT DESC